apiVersion: v1
kind: Pod
metadata:
  name: testpod
  labels:
    name: myapp
spec:
  containers:
  - name: webapp
    image: mylandmarktech/web-app
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8081
